require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/storages", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Storage. As you add validations to Storage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # StoragesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Storage.create! valid_attributes
      get storages_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      storage = Storage.create! valid_attributes
      get storage_url(storage), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Storage" do
        expect {
          post storages_url,
               params: { storage: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Storage, :count).by(1)
      end

      it "renders a JSON response with the new storage" do
        post storages_url,
             params: { storage: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Storage" do
        expect {
          post storages_url,
               params: { storage: invalid_attributes }, as: :json
        }.to change(Storage, :count).by(0)
      end

      it "renders a JSON response with errors for the new storage" do
        post storages_url,
             params: { storage: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested storage" do
        storage = Storage.create! valid_attributes
        patch storage_url(storage),
              params: { storage: new_attributes }, headers: valid_headers, as: :json
        storage.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the storage" do
        storage = Storage.create! valid_attributes
        patch storage_url(storage),
              params: { storage: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the storage" do
        storage = Storage.create! valid_attributes
        patch storage_url(storage),
              params: { storage: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested storage" do
      storage = Storage.create! valid_attributes
      expect {
        delete storage_url(storage), headers: valid_headers, as: :json
      }.to change(Storage, :count).by(-1)
    end
  end
end
